name: Security Hardening

# Define triggers for the workflow; it ignores pushes to branches prefixed with 'dependabot/'
# and responds to pull requests targeting any branch in the repository.
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

# Manage concurrency to ensure that only one instance of this workflow runs at a time per branch/ref,
# cancelling any in-progress instances when a new one starts.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read-only to enhance security.
permissions: read-all

jobs:
  security-hardening:
    name: Harden Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Use a specific SHA to checkout the code, ensuring the action is secure and hasn't been tampered with.
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Ensure SHA pinned actions
        # Utilize a community GitHub Action to verify all used actions are pinned to a SHA for enhanced security.
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@76d1d8e0b075d7190b5d59b86da91c7bdbcc99b2 # v3.0.7
